In [2]:
import pandas as pd
import numpy as np

In [4]:
dataset_raw = pd.read_csv("fifa21_raw_data_v2.csv", low_memory=False)

In [6]:
dataset_raw.shape

(18979, 77)

In [7]:
dataset_raw.columns

Index(['ID', 'Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Age',
       '↓OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height', 'Weight',
       'Preferred Foot', 'BOV', 'Best Position', 'Joined', 'Loan Date End',
       'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='str')

In [9]:
dataset_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                18979 non-null  int64
 1   Name              18979 non-null  str
 2   LongName          18979 non-null  str
 3   photoUrl          18979 non-null  str
 4   playerUrl         18979 non-null  str
 5   Nationality       18979 non-null  str
 6   Age               18979 non-null  int64
 7   ↓OVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   Club              18979 non-null  str
 10  Contract          18979 non-null  str
 11  Positions         18979 non-null  str
 12  Height            18979 non-null  str
 13  Weight            18979 non-null  str
 14  Preferred Foot    18979 non-null  str
 15  BOV               18979 non-null  int64
 16  Best Position     18979 non-null  str
 17  Joined            18979 non-null  str
 18  Loan Date End     1013 non-null   str
 19  Value             18979 non-null  str
 20  Wage              18979 non-null  str
 21  Release Clause    18979 non-null  str
 22  Attacking         18979 non-null  int64
 23  Crossing          18979 non-null  int64
 24  Finishing         18979 non-null  int64
 25  Heading Accuracy  18979 non-null  int64
 26  Short Passing     18979 non-null  int64
 27  Volleys           18979 non-null  int64
 28  Skill             18979 non-null  int64
 29  Dribbling         18979 non-null  int64
 30  Curve             18979 non-null  int64
 31  FK Accuracy       18979 non-null  int64
 32  Long Passing      18979 non-null  int64
 33  Ball Control      18979 non-null  int64
 34  Movement          18979 non-null  int64
 35  Acceleration      18979 non-null  int64
 36  Sprint Speed      18979 non-null  int64
 37  Agility           18979 non-null  int64
 38  Reactions         18979 non-null  int64
 39  Balance           18979 non-null  int64
 40  Power             18979 non-null  int64
 41  Shot Power        18979 non-null  int64
 42  Jumping           18979 non-null  int64
 43  Stamina           18979 non-null  int64
 44  Strength          18979 non-null  int64
 45  Long Shots        18979 non-null  int64
 46  Mentality         18979 non-null  int64
 47  Aggression        18979 non-null  int64
 48  Interceptions     18979 non-null  int64
 49  Positioning       18979 non-null  int64
 50  Vision            18979 non-null  int64
 51  Penalties         18979 non-null  int64
 52  Composure         18979 non-null  int64
 53  Defending         18979 non-null  int64
 54  Marking           18979 non-null  int64
 55  Standing Tackle   18979 non-null  int64
 56  Sliding Tackle    18979 non-null  int64
 57  Goalkeeping       18979 non-null  int64
 58  GK Diving         18979 non-null  int64
 59  GK Handling       18979 non-null  int64
 60  GK Kicking        18979 non-null  int64
 61  GK Positioning    18979 non-null  int64
 62  GK Reflexes       18979 non-null  int64
 63  Total Stats       18979 non-null  int64
 64  Base Stats        18979 non-null  int64
 65  W/F               18979 non-null  str
 66  SM                18979 non-null  str
 67  A/W               18979 non-null  str
 68  D/W               18979 non-null  str
 69  IR                18979 non-null  str
 70  PAC               18979 non-null  int64
 71  SHO               18979 non-null  int64
 72  PAS               18979 non-null  int64
 73  DRI               18979 non-null  int64
 74  DEF               18979 non-null  int64
 75  PHY               18979 non-null  int64
 76  Hits              16384 non-null  str
dtypes: int64(54), str(23)
memory usage: 11.1 MB

In [10]:
dataset_raw.describe()

,ID,Age,↓OVA,POT,BOV,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,...,GK Positioning,GK Reflexes,Total Stats,Base Stats,PAC,SHO,PAS,DRI,DEF,PHY
count,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,...,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000
mean,226403.384794,25.194109,65.718636,71.136414,66.751726,248.938142,49.688392,45.842405,51.942726,58.768112,...,16.217187,16.519627,1595.286949,355.702197,67.453975,53.457031,57.681016,62.875020,49.866221,64.368934
std,27141.054157,4.710520,6.968999,6.114635,6.747193,74.299428,18.131153,19.567081,17.294409,14.519106,...,17.002239,17.854079,269.874789,40.761117,10.677859,13.827425,10.081857,9.927415,16.443213,9.601883
min,41.000000,16.000000,47.000000,47.000000,48.000000,42.000000,6.000000,3.000000,5.000000,7.000000,...,2.000000,2.000000,747.000000,232.000000,25.000000,16.000000,25.000000,25.000000,12.000000,28.000000
25%,210135.000000,21.000000,61.000000,67.000000,62.000000,222.000000,38.000000,30.000000,44.000000,54.000000,...,8.000000,8.000000,1452.000000,327.000000,61.000000,44.000000,51.000000,57.000000,35.000000,58.000000
50%,232418.000000,25.000000,66.000000,71.000000,67.000000,263.000000,54.000000,49.000000,55.000000,62.000000,...,11.000000,11.000000,1627.000000,356.000000,68.000000,56.000000,58.000000,64.000000,53.000000,65.000000
75%,246922.500000,29.000000,70.000000,75.000000,71.000000,297.000000,63.000000,62.000000,64.000000,68.000000,...,14.000000,14.000000,1781.000000,384.000000,75.000000,64.000000,64.000000,69.000000,63.000000,71.000000
max,259216.000000,53.000000,93.000000,95.000000,93.000000,437.000000,94.000000,95.000000,93.000000,94.000000,...,91.000000,90.000000,2316.000000,498.000000,96.000000,93.000000,93.000000,95.000000,91.000000,91.000000

In [11]:
dataset_raw.head()

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595

In [16]:
dataset_raw.isnull().sum().sort_values(ascending=False)

Loan Date End    17966
Hits              2595
LongName             0
Name                 0
ID                   0
                 ...
PAC                  0
PAS                  0
DRI                  0
DEF                  0
PHY                  0
Length: 77, dtype: int64

In [19]:
dataset_raw.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
18974    False
18975    False
18976    False
18977    False
18978    False
Length: 18979, dtype: bool

In [24]:
dataset_raw.dtypes

ID           int64
Name           str
LongName       str
photoUrl       str
playerUrl      str
             ...
PAS          int64
DRI          int64
DEF          int64
PHY          int64
Hits           str
Length: 77, dtype: object

In [27]:
dataset1=dataset_raw.copy()

In [61]:
dataset1["Wage"].head()

0    560000.0
1    220000.0
2    125000.0
3    370000.0
4    270000.0
Name: Wage, dtype: float64

In [59]:
dataset1["Value"].head()

0    103500000.0
1     63000000.0
2    120000000.0
3    129000000.0
4    132000000.0
Name: Value, dtype: float64

In [47]:
def currency(value):
    value=value.replace("€","")
    if "M" in value :
      return  float(value.replace("M",""))*1_000_000
    elif "K" in value :
       return float(value.replace("K",""))*1_000
    else:
        return float(value)

In [58]:
dataset1["Value"]=(dataset1["Value"].apply(currency))

In [60]:
dataset1["Wage"]=(dataset1["Wage"].apply(currency))

In [87]:
def incm(height):
    if "cm" in height:
        return float(height.replace("cm",""))
    if "'" in height:
        if'"' in height : 
           height=height.replace('"',"")
        feet,inch=height.split("'")
        feet = float(feet)
        inch = float(inch)
    else :
        return (height)
    return (inch*2.54+feet*30.48)

In [86]:
dataset1["Height"]=dataset1["Height"].apply(incm)

In [88]:
dataset1["Height"].head(500)

0      170.0
1      187.0
2      188.0
3      181.0
4      175.0
       ...
495    184.0
496    184.0
497    177.0
498    185.0
499    188.0
Name: Height, Length: 500, dtype: float64

In [98]:
def inkg(weight):
    if "kg" in weight:
        return float(weight.replace('kg',''))
    if "lbs" in weight:
        return (float(weight.replace('lbs',''))*.454)

In [99]:
dataset1["Weight"]=dataset1["Weight"].apply(inkg)

In [100]:
dataset1["Weight"]

0        72.0
1        83.0
2        87.0
3        70.0
4        68.0
         ...
18974    66.0
18975    65.0
18976    74.0
18977    69.0
18978    75.0
Name: Weight, Length: 18979, dtype: float64

In [115]:
dataset1["SM"].head()

0    4.0
1    5.0
2    1.0
3    4.0
4    5.0
Name: SM, dtype: float64

In [112]:
dataset1["SM"]=dataset1["SM"].str.replace('★','').astype(float)

In [113]:
dataset1["IR"]=dataset1["IR"].str.replace('★','').astype(float)

In [114]:
dataset1["W/F"]=dataset1["W/F"].str.replace('★','').astype(float)

In [118]:
dataset1["Release Clause"]=dataset1["Release Clause"].apply(currency)

In [119]:
dataset1["Release Clause"]

0        138400000.0
1         75900000.0
2        159400000.0
3        161000000.0
4        166500000.0
            ...
18974        70000.0
18975       165000.0
18976       131000.0
18977        88000.0
18978        79000.0
Name: Release Clause, Length: 18979, dtype: float64

In [135]:
dataset1["Hits"]=dataset1["Hits"].fillna("0")

In [137]:
def hit(value):
    value=str(value)
    if "K" in value:
        return (float(value.replace('K',''))*1000)
    else :
        return float(value)

In [138]:
dataset1["Hits"]=dataset1["Hits"].apply(hit)

In [139]:
dataset1["Hits"]

0        771.0
1        562.0
2        150.0
3        207.0
4        595.0
         ...
18974      0.0
18975      0.0
18976      0.0
18977      0.0
18978      0.0
Name: Hits, Length: 18979, dtype: float64

In [140]:
dataset1["Contract"]

0        2004 ~ 2021
1        2018 ~ 2022
2        2014 ~ 2023
3        2015 ~ 2023
4        2017 ~ 2022
            ...
18974    2018 ~ 2022
18975    2020 ~ 2021
18976    2019 ~ 2020
18977    2020 ~ 2022
18978    2019 ~ 2023
Name: Contract, Length: 18979, dtype: str

In [142]:
dataset1[["Contract Start", "Contract End"]] = (
    dataset1["Contract"].str.split(" ~ ", expand=True)
)

In [143]:
dataset1.head()

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Contract Start,Contract End
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,5.0,85,92,91,95,38,65,771.0,2004,2021
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,5.0,89,93,81,89,35,77,562.0,2018,2022
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,3.0,87,92,78,90,52,90,150.0,2014,2023
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,...,4.0,76,86,93,88,64,78,207.0,2015,2023
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,...,5.0,91,85,86,94,36,59,595.0,2017,2022

In [ ]:
names = dataset1["LongName"].str.split(" ", expand=True)
print(names.shape)

             0         1       2       3       4    5
0       Lionel     Messi     NaN     NaN     NaN  NaN
1           C.   Ronaldo     dos  Santos  Aveiro  NaN
2          Jan     Oblak     NaN     NaN     NaN  NaN
3        Kevin        De  Bruyne     NaN     NaN  NaN
4       Neymar        da   Silva  Santos     Jr.  NaN
...        ...       ...     ...     ...     ...  ...
18974       Ao       Xia     NaN     NaN     NaN  NaN
18975      Ben     Hough     NaN     NaN     NaN  NaN
18976    Ronan  McKinley     NaN     NaN     NaN  NaN
18977  Zhen'ao      Wang     NaN     NaN     NaN  NaN
18978     Xiao      Zhou     NaN     NaN     NaN  NaN

[18979 rows x 6 columns]

In [151]:
dataset1[["name0","name1","name2","name3","name4","name5"]]=(dataset1["LongName"].str.split(" ", expand=True))

In [155]:
dataset1[["name0","name1","name2","name3","name4","name5"]]

         name0     name1   name2   name3   name4 name5
0       Lionel     Messi     NaN     NaN     NaN   NaN
1           C.   Ronaldo     dos  Santos  Aveiro   NaN
2          Jan     Oblak     NaN     NaN     NaN   NaN
3        Kevin        De  Bruyne     NaN     NaN   NaN
4       Neymar        da   Silva  Santos     Jr.   NaN
...        ...       ...     ...     ...     ...   ...
18974       Ao       Xia     NaN     NaN     NaN   NaN
18975      Ben     Hough     NaN     NaN     NaN   NaN
18976    Ronan  McKinley     NaN     NaN     NaN   NaN
18977  Zhen'ao      Wang     NaN     NaN     NaN   NaN
18978     Xiao      Zhou     NaN     NaN     NaN   NaN

[18979 rows x 6 columns]

In [ ]:
dataset1.isnull().sum().sort_values(ascending=False).head(8)

name5            18975
name4            18789
Loan Date End    17966
name3            17737
name2            15290
Contract End      1250
playerUrl            0
↓OVA                 0
dtype: int64

In [163]:
dataset1["Loan Date End"].head(20)

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
15    NaN
16    NaN
17    NaN
18    NaN
19    NaN
Name: Loan Date End, dtype: str

In [164]:
dataset1["Loan Date End"].unique()

<StringArray>
[        nan, '30-Jun-21', '31-Dec-20', '30-Jan-21', '30-Jun-22', '31-May-21',
  '5-Jul-21', '31-Dec-21',  '1-Jul-21',  '1-Jan-21', '31-Aug-21', '31-Jan-21',
 '30-Dec-21', '23-Jun-21',  '3-Jan-21', '27-Nov-21', '17-Jan-21', '30-Jun-23',
 '31-Jul-21', '22-Nov-20', '31-May-22', '30-Dec-20',  '4-Jan-21', '30-Nov-20',
  '1-Aug-21']
Length: 25, dtype: str

In [189]:
dataset1["Loan Date End"] = pd.to_datetime(dataset1["Loan Date End"])

In [190]:
dataset1["Loan Date End"].unique

<bound method Series.unique of 0       NaT
1       NaT
2       NaT
3       NaT
4       NaT
         ..
18974   NaT
18975   NaT
18976   NaT
18977   NaT
18978   NaT
Name: Loan Date End, Length: 18979, dtype: datetime64[s]>

In [198]:
dataset1["Positions"]

0        RW, ST, CF
1            ST, LW
2                GK
3           CAM, CM
4           LW, CAM
            ...
18974            CB
18975            CM
18976            CM
18977            RW
18978        CB, LB
Name: Positions, Length: 18979, dtype: str

In [205]:
dataset1[["pos1","pos2","pos3"]]=dataset1["Positions"].str.split(',' ,expand=True)

In [206]:
dataset1[["pos1","pos2","pos3"]]

      pos1  pos2 pos3
0       RW    ST   CF
1       ST    LW  NaN
2       GK   NaN  NaN
3      CAM    CM  NaN
4       LW   CAM  NaN
...    ...   ...  ...
18974   CB   NaN  NaN
18975   CM   NaN  NaN
18976   CM   NaN  NaN
18977   RW   NaN  NaN
18978   CB    LB  NaN

[18979 rows x 3 columns]

In [227]:
dataset1.isnull().sum().sort_values(ascending=False).head(10)

Loan Date End    17966
Contract End      1250
LongName             0
ID                   0
playerUrl            0
Nationality          0
Age                  0
Name                 0
↓OVA                 0
POT                  0
dtype: int64

In [ ]:
dataset1["name4"] = dataset1["name5"].fillna("Empty")

In [215]:
dataset1["name4"] = dataset1["name5"].fillna("Empty")

In [222]:
dataset1["name3"] = dataset1["name5"].fillna("Empty")

In [224]:
dataset1["name2"] = dataset1["name5"].fillna("Empty")

In [225]:
dataset1["pos3"] = dataset1["pos3"].fillna("Empty")

In [226]:
dataset1["pos2"] = dataset1["pos2"].fillna("Empty")

In [230]:
dataset1.to_excel("Fifa21_cleaned.xlsx", index=False)

In [231]:
dataset1.to_csv("Fifa21_cleaned", index=False)

In [232]:
dataset1["Joined"] = pd.to_datetime(dataset1["Joined"])
dataset1["Loan Date End"] = pd.to_datetime(dataset1["Loan Date End"])

C:\Users\kusha\AppData\Local\Temp\ipykernel_21128\1660341056.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dataset1["Joined"] = pd.to_datetime(dataset1["Joined"])

In [233]:
dataset1["original_pos"]=dataset_raw["Positions"]

In [234]:
dataset1.drop(
    columns=["name0","name1","name2","name3","name4","name5"],
    inplace=True
)

In [235]:
dataset1.to_csv("Fifa21_cleaned", index=False)

In [236]:
dataset1.to_excel("Fifa21_cleaned.xlsx", index=False)